# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - Ajustor
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
        - Added features
    - title: Bugs killer 🐛
      labels:
        - Bug fixes
    - title: Other Changes
      labels:
        - "*"