stages:
  - install
  - build
  # - deploy
  # - linux
  # - windows
  # - macos
  # - android
  # - ios

variables:
  CARGO_TERM_COLOR: always

install:
  stage: install
  image: oven/bun
  cache:  # Cache modules in between jobs
    key: 
      files:
        - package-lock.json
    paths:
      - node_modules
  script:
    - bun install

linux:
  stage: build
  image: rust:latest
  script:
    - curl -fsSL https://bun.sh/install | bash
    - source ~/.bashrc
    - rustup target add aarch64-unknown-linux-gnu
    - apt-get update; apt-get install -y ibwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev librsvg2-dev
    # - cargo install tauri-cli
    # - cargo-tauri build
    - bun tauri build --target aarch64-unknown-linux-gnu

  artifacts:
    paths:
      - target/release/bundle/deb
    expire_in: 1 week

windows:
  stage: build
  image: rust:latest
  script:
    - rustup target add x86_64-pc-windows-msvc aarch64-pc-windows-msvc
    - apt-get update; apt-get install -y ibwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev librsvg2-dev mingw-w64
    - curl -fsSL https://bun.sh/install | bash
    - source ~/.bashrc
    - cargo install tauri-cli
    - cargo-tauri build --target x86_64-pc-windows-msvc
    - cargo-tauri build --target aarch64-pc-windows-msvc

  artifacts:
    paths:
      - target/release/bundle/msi
    expire_in: 1 week

macos:
  stage: build
  image: rust:latest
  script:
    - curl -fsSL https://bun.sh/install | bash
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - source ~/.bashrc
    - rustup target add x86_64-apple-darwin aarch64-apple-darwin
    - brew install openssl@1.1 libwebkit2gtk
    - cargo install tauri-cli
    - cargo-tauri build --target x86_64-apple-darwin
    - cargo-tauri build --target aarch64-apple-darwin

  artifacts:
    paths:
      - target/release/bundle/dmg
    expire_in: 1 week

# android:
#   stage: android
#   image: rust:latest
#   script:
#     - apt install -y openjdk-18-jdk
#     - wget https://redirector.gvt1.com/edgedl/android/studio/ide-zips/2024.1.1.7/android-studio-2024.1.1.7-linux.tar.gz
#     - tar -zxvf android-studio-2024.1.1.7-linux.tar.gz
#     - sudo mv android-studio /opt/
#     - sudo ln -sf /opt/android-studio/bin/studio.sh /bin/android-studio
#     - export ANDROID_HOME="$HOME/Android/Sdk"; export NDK_HOME="$ANDROID_HOME/ndk/$(ls -1 $ANDROID_HOME/ndk)"; export JAVA_HOME=/opt/android-studio/jbr
#     - rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
#     - apt-get update; apt-get install -y ibwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev librsvg2-dev
#     - cargo install tauri-cli
#     - cargo-tauri build --target aarch64-linux-android
#     - cargo-tauri build --target i686-linux-android
#     - cargo-tauri build --target armv7-linux-androideabi
#     - cargo-tauri build --target x86_64-linux-android
#     - tar -czf sending_unicorns_android.tar.gz target/aarch64-linux-android/debug/sending_unicorns.apk target/i686-linux-android/debug/sending_unicorns.apk target/armv7-linux-androideabi/debug/sending_unicorns.apk target/x86_64-linux-android/debug/sending_unicorns.apk

#   artifacts:
#     paths:
#       - sending_unicorns_android.tar.gz
#     expire_in: 1 week
    
# ios:
#   stage: ios
#   image: rust:latest
#   script:
#     - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#     - brew install cocoapods
#     - rustup target add aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim
#     - apt-get update; apt-get install -y ibwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev librsvg2-dev
#     - cargo install tauri-cli
#     - cargo-tauri build --target arm64e-apple-ios
#     - cargo-tauri build --target x86_64-apple-ios
#     - cargo-tauri build --target aarch64-apple-ios-sim
#     - tar -czf sending_unicorns_ios.tar.gz target/arm64e-apple-ios/debug/sending_unicorns.ipa target/x86_64-apple-ios/debug/sending_unicorns.ipa target/aarch64-apple-ios-sim/debug/sending_unicorns.ipa

#   artifacts:
#     paths:
#       - sending_unicorns_ios.tar.gz
#     expire_in: 1 week
