stages:
  - setup
  - build
  - packages

# Variables globales
variables:
  RUST_VERSION: "latest"
  TAURI_VERSION: "latest"
  NODE_CACHE_PATH: "node_modules"

setup:
  stage: setup
  image: rust:${RUST_VERSION}
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - curl -fsSL https://bun.sh/install | bash
    - source ~/.bashrc
    - bun i

build_view:
  stage: build
  image: oven/bun
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - bun run build
  artifacts:
    paths:
      - build
    expire_in: 1 hour

linux:
  stage: packages
  image: rust:${RUST_VERSION}
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - apt update
    - apt install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev -y
    - rustup target add x86_64-unknown-linux-gnu
    - cargo install tauri-cli
    - cargo-tauri build --target x86_64-unknown-linux-gnu
  artifacts:
    paths:
      - target/release/bundle/

windows:
  stage: packages
  image: rust:${RUST_VERSION}
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - apt update
    - apt install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev nsis -y
    - rustup target add x86_64-pc-windows-gnu
    - cargo install tauri-cli
    - cargo install xwin
    - xwin splat --output ~/.xwin --disable-symlinks -y
    - bun tauri build --target x86_64-pc-windows-gnu
  artifacts:
    paths:
      - target/release/bundle/

mac:
  stage: packages
  image: rust:${RUST_VERSION}
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - apt update
    - apt install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev -y
    - rustup target add x86_64-apple-darwin
    - cargo install tauri-cli
    - cargo-tauri build --target x86_64-apple-darwin
  artifacts:
    paths:
      - target/release/bundle/

other_linux:
  stage: packages
  image: ivangabriele/tauri:debian-bullseye-18
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - rustup target add x86_64-unknown-linux-gnu
    - cargo install tauri-cli
    - cargo-tauri build --target x86_64-unknown-linux-gnu
  artifacts:
    paths:
      - target/release/bundle/