stages:
  - setup
  - build
  - packages

# Variables globales
variables:
  RUST_VERSION: "latest"
  TAURI_VERSION: "latest"
  NODE_CACHE_PATH: "node_modules"

setup:
  stage: setup
  image: rust:${RUST_VERSION}
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - curl -fsSL https://bun.sh/install | bash
    - source ~/.bashrc
    - bun i

build_view:
  stage: build
  image: oven/bun
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - bun run build
  artifacts:
    paths:
      - build
    expire_in: 1 hour

windows:
  stage: packages
  image: ajustor/tauri2-cli:windows
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - rustup target add x86_64-pc-windows-gnu 
    - export CC_x86_64_pc_windows_gnu=x86_64-w64-mingw32-gcc
    - export CXX_x86_64_pc_windows_gnu=x86_64-w64-mingw32-g++
    - export AR_x86_64_pc_windows_gnu=x86_64-w64-mingw32-ar
    - export CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER=x86_64-w64-mingw32-gcc
    - cargo-tauri build --target x86_64-pc-windows-gnu --no-bundle
    - makensis windows_builder.nsi
  artifacts:
    paths:
      - "SendingUnicorns Setup.exe"

# mac:
#   stage: packages
#   image: ajustor/tauri-cli:macos
#   cache:
#     key: tauri-cli-cache
#     paths:
#       - ${NODE_CACHE_PATH}
#   script:
#     - rustup target add x86_64-apple-darwin
#     - cargo install tauri-cli
#     - bun build --target x86_64-apple-darwin
#     - mv src-tauri/target/x86_64-apple-darwin/release/bundle/ output
#   artifacts:
#     paths:
#       - output

linux:
  stage: packages
  image: ajustor/tauri2-cli:linux
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - cargo-tauri build --target x86_64-unknown-linux-gnu
    - mv src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/ output
  artifacts:
    paths:
      - output