stages:
  - setup
  - build
  - packages

# Variables globales
variables:
  RUST_VERSION: "latest"
  TAURI_VERSION: "latest"
  NODE_CACHE_PATH: "node_modules"

setup:
  stage: setup
  image: rust:${RUST_VERSION}
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - curl -fsSL https://bun.sh/install | bash
    - source ~/.bashrc
    - bun i

build_view:
  stage: build
  image: oven/bun
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - bun run build
  artifacts:
    paths:
      - build
    expire_in: 1 hour

windows:
  stage: packages
  image: ajustor/tauri-cli:windows
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - cargo-tauri build --runner cargo-xwin --target x86_64-pc-windows-msvc
  artifacts:
    paths:
      - src-tauri/target/x86_64-pc-windows-msvc/release/bundle/

mac:
  stage: packages
  image: ajustor/tauri-cli:macos
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - rustup target add x86_64-apple-darwin
    - cargo install tauri-cli
    - cargo-tauri build --target x86_64-apple-darwin
  artifacts:
    paths:
      - src-tauri/target/x86_64-apple-darwin/release/bundle/

linux:
  stage: packages
  image: ajustor/tauri-cli:linux
  cache:
    key: tauri-cli-cache
    paths:
      - ${NODE_CACHE_PATH}
  script:
    - cargo-tauri build --target x86_64-unknown-linux-gnu
  artifacts:
    paths:
      - src-tauri/target/x86_64-unknown-linux-gnu/release/bundle/