steps:
  - name: Linux
    image: rust:latest
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - rustup default stable
      - apt-get update
      - apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev libxcb-shape0-dev libxcb-xfixes0-dev libxdo-dev;
      - curl -fsSL https://bun.sh/install | bash
      - source ~/.bashrc
      - cargo install tauri-cli
      - bun tauri build

  - name: Windows
    runs-on: windows-latest
    image: rust:latest
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - rustup default stable
      - powershell -c "irm bun.sh/install.ps1 | iex"
      - cargo install tauri-cli
      - bun tauri build

  - name: Zip Artifact (Linux)
    image: rust:latest
    commands:
      - zip sending_unicorns_linux.zip target/release/bundle/*deb target/release/bundle/appimage/*AppImage -r

  - name: Zip Artifact (Windows)
    image: rust:latest
    runs-on: windows-latest
    commands:
      - Compress-Archive -Path target/release/bundle/nsis/*exe,target/release/bundle/msi/*msi -DestinationPath sending_unicorns_windows.zip

  - name: Upload Artifact (Linux)
    image: rust:latest
    uses: https://github.com/actions/upload-artifact@v4
    with:
      name: Sending Unicorns (Linux)
      path: sending_unicorns_linux.zip

  - name: Upload Artifact (Windows)
    image: rust:latest
    uses: https://github.com/actions/upload-artifact@v4
    with:
      name: Sending Unicorns (Windows)
      path: sending_unicorns_windows.zip